### ISSUE TITLE
IPFS companion causes normal websites not to load

### ISSUE THREAD

**Issue by kodxana** [ipfs/ipfs-companion#1003]
**Describe the bug**
After one day of using IPFS companion in Brave normal http/https websites do not load. After removing IPFS companion websites load corectly.

**To Reproduce**
1. Run IPFS on another machine in LAN network (1 day)
2. Install companion in Brave
3. Try load any http page
5. Remove companion
6. Try load http page

**Expected behavior**
Companion should not affect browsing of http websites

**Desktop (please complete the following information):**
 - OS: Windox 10 x64
 - Browser: Brave
 - Version 1.24.89

**Comment by lidel** [comment]
@kodxana   could you please provide example of URL that is impacted by this?
Is this specific to some websites (eg. ones with dnslink) or is the issue blocking all websites?

**Comment by kodxana** [comment]
I noticed that browser do not load http websites (clearnet ones) when http gateway is not accesible. Is this a expected behavior?

**Comment by lidel** [comment]
It is not. How can we reproduce this?
What error is displayed?

**Comment by kodxana** [comment]
Setup IPFS node on remote machine on LAN. Setup SSH tunnel for HTTP Gateway and API. Enable IPFS in brave browser. If you try load any website before you start SSH tunnel websites will load infinite. When you start SSH Tunnel and gatway starts to become availible all websites load corectly.

**Comment by FayneAldan** [comment]
I have a very similar issue but with a **locally hosted gateway** (127.0.0.1).

 - OS: Windows 10 Pro 21H1 Build 19043.1055
 - Browser: Microsoft Edge, Brave, and Google Chrome

I have a video of this issue occurring in MS Edge, but I experience the same issue with Google Chrome and Brave (using the local gateway):
https://youtu.be/ZWKm-4GfG6M

It's also worth noting that this issue doesn't occur when using Brave's built-in IPFS gateway, so I'm assuming it's some sort of corrupted file or bad setting in the gateway. Here's my config, if it helps:
https://gist.github.com/FayneAldan/cad069b92591746e1bdf2ea13f49a826

**Comment by lidel** [comment]
@kodxana I am not able to reproduce. Could  this be a Windows thing? Is the problem, still present after you go to Companion Preferences and click "Reset Everything" ?

>  ![2021-06-24--15-57-35](https://user-images.githubusercontent.com/157609/123275786-eb590f80-d504-11eb-840f-7b90b88c66e1.png)


@FayneAldan thanks  for the info, some additional questions:

- Does the "reset" above help?
- That constant offline/online switch suggests either problem with daemon, or access to the API port being blocked by something.
  - Are you running any firewall / antivirus software on Windows?
  - How do you run your go-ipfs (daemon or ipfs-desktop)? Are you able to confirm it does not crash/restart all the time?

**Comment by FayneAldan** [comment]
Resetting does nothing. The only firewall I'm using is Windows Firewall and it works half the time.
