### ISSUE TITLE
IPFS companion blocks on api/v0/name/resolve/ when opening a webpage

### ISSUE THREAD

**Issue by rihardsk** [ipfs/ipfs-companion#1004]
When i open some sites after a longer time (1-2 days) of not doing so, i experience a delay lasting multiple seconds before the site opens. I've tracked this down to being caused by the the IPFS companion plugin. When opening, e.g., stackoverflow.com, it blocks on a request to http://localhost:8081/api/v0/name/resolve/stackoverflow.com?r=false (i've changed the gateway port to 8081) for around 20 seconds and only then does the site open. I've determened this by using the Firefox profiler (profiler.firefox.com), see the screenshot below. Subsequent attempts to open stackoverflow.com happen without the delay.

**To Reproduce**
1. Use go-ipfs and the IPFS companion plugin on Firefox
2. Don't open stackoverflow.com for 2 days
3. Try to open stackoverflow.com in Firefox
4. Experience a 20 second long wait time until the site opens

**Expected behavior**
There isn't a 20 second delay when opening the site

**Screenshots**
![image](https://user-images.githubusercontent.com/1666746/120112208-916f5f00-c17d-11eb-8f97-2b9ca4074be1.png)

**Desktop (please complete the following information):**
 - OS: Linux (Arch)
 - Browser Firefox
 - Version 88
 - Companion version - v2.19.0

**Additional context**
Why does the IPFS companion have to query the gateway about stackoverflow.com? Is this to determine whether the domain has a TXT record for DNSLink? I have left the `DNSLink Lookup Policy` setting set to the the default `Check after HTTP request` value in the companion settings which should disable blocking on DNSLink responses, afaik.

**Comment by lidel** [comment]
This is definitely not expected behavior, DNSLink checks should happen asynchronously. 

DNSLink lookup cache can be purged by restarting Firefox, no need to wait 2 days, but.. was not able to reproduce this.
Stab in the dark: are you running any antivirus software on Windows that could be hijacking HTTP requests?
