### ISSUE TITLE
ipfs://CIDv0 (ipfs://Qm…) becomes lowercase and doesn't work on firefox 89

### ISSUE THREAD

**Issue by jsmaniac** [ipfs/ipfs-companion#1006]
When accessing ipfs://QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG, the link is converted to lowercase, and an error message appears because of that.

**To Reproduce**

1. Install ipfs-companion 2.19.0 on Firefox 89 from https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/
2. start `ipfs daemon` on the command-line
3. copy-paste this into the URL bar: `ipfs://QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG`
4. the url rapidly changes to `ipfs://qmuvtksryjpaxut7dr9fpkq6aokhhem7eg1zhgl56haklg` and then to `https://dweb.link/ipfs/qmuvtksryjpaxut7dr9fpkq6aokhhem7eg1zhgl56haklg` which shows the following error:

```
invalid ipfs path: invalid path "/ipfs/qmuvtksryjpaxut7dr9fpkq6aokhhem7eg1zhgl56haklg": invalid CID: selected encoding not supported (possible lowercased CIDv0; consider converting to a case-agnostic CIDv1, such as base32)
```

**Expected behaviour**

The URL should stay `ipfs://QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG` or be converted to `http://QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG.ipfs.localhost:8080/` or some other proxy, and a page containing the text `Hello IPFS` should appear.

**Screenshots**
![20210607_05h39m26s_grim](https://user-images.githubusercontent.com/299872/120959910-c0c03600-c752-11eb-8665-09000af1b3ea.png)

**Desktop**
 - OS: Linux (Ubuntu 20.04 Focal, ipfs installed via nixpkgs)
 - Browser: Firefox 89.0 64-bit (installed via nixpkgs)
 - `ipfs --version`: `ipfs version 0.8.0`
 -  ipfs-companion version: 2.19.0

**Additional context**

- Entering https://dweb.link/ipfs/QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)
- Entering ipfs://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)

- Entering /ipfs/QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG in the URL bar works (and redirects to file:///ipfs/QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG)
- Entering /ipfs/bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu in the URL bar works (and redirects to file:///ipfs/bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu)

- Entering QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG.ipfs.localhost:8080 in the URL bar *DOES NOT WORK* (it gets redirected to http://qmuvtksryjpaxut7dr9fpkq6aokhhem7eg1zhgl56haklg.ipfs.localhost:8080/)
- Entering bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080 in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)

- Entering ipfs://ipfs/QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)
- Entering ipfs://ipfs/bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)

- Entering ipfs://./QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)
- Entering ipfs://./bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)

- Entering ipfs:./QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)
- Entering ipfs:./bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu in the URL bar works (and redirects to http://bafybeic3m55e3k75my22xepbnga5m7gao5dzvtwpnyjkebjqir54dlngfu.ipfs.localhost:8080/)

A similar issue has been reported in the past, and closed as fixed: https://github.com/ipfs/ipfs-companion/issues/815

**Comment by lidel** [comment]
Thank you for reporting this.

Unfortunately, the lowercasing is performed by Firefox before URL is passed to gateway or can be converted to CIDv1 by Companion, so we can't do anything about it. 

You should follow the advice from the error message and convert CID to case-insensitive base32.
This can be done on https://cid.ipfs.io or  in command line via `ipfs cid base32 Qm..`

**Comment by Atemu** [comment]
Has anyone gotten in touch with Mozilla about this? Perhaps they could be trivially alleviate this issue on their end.

Obviously CIDv1 is the solution going forward but there are lots of CIDv0 links still out there. My first real contact with IPFS happened just a few minutes ago and it was a CIDv0 which triggered this issue. It's not a *huge* problem since linkifying ipfs URLs usually obviates the need for pasting one into the browser bar but that's not enabled by default.

I also got a very user-unfriendly error message which isn't great:

```
invalid ipfs path: invalid path "/ipfs/qmyhcm6myg2fsgfik5hksa8eahwrpq2wdpxxmjhamdsn17": invalid CID: selected encoding not supported (possible lowercased CIDv0; consider converting to a case-agnostic CIDv1, such as base32)
```

**Comment by lidel** [comment]
It  is not just Mozilla, other apps and libraries force-lowercase on URIs as well.
Expecting that all user agents change the way they parse URI/URL is not realistic imo – better to invest time in things like finishing cidv1 migration: https://github.com/ipfs/go-ipfs/pull/8185

The best we can do for CIDv0 is to improve error message when they get broken by a forced lowercase.
You can PR improvements against this line: https://github.com/ipfs/go-path/blob/v0.1.1/path.go#L187
