### ISSUE TITLE
Issue with Default Public Gateway on Firefox

### ISSUE THREAD

**Issue by coltonsteeve** [ipfs/ipfs-companion#1007]
**Describe the bug**
The browser threw and error instead of redirecting to my website when I try to use ipfs://. It seems to be making my ipfs hash all lowercase instead of keeping the uppercase letters.

**Error Message**
invalid ipfs path: invalid path "/ipfs/ipfs_hash": invalid CID: selected encoding not supported (possible lowercased CIDv0; consider converting to a case-agnostic CIDv1, such as base32)

**Expected behavior**
The browser should have redirected to my website.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 89

**Comment by lidel** [comment]
Thank you for reporting this, see https://github.com/ipfs/ipfs-companion/issues/1006#issuecomment-859581056
