### ISSUE TITLE
Please allow using IPFS Companion on Brave without using Brave's local node

### ISSUE THREAD

**Issue by FayneAldan** [ipfs/ipfs-companion#1020]
**Is your feature request related to a problem? Please describe.**
I can't use IPFS Companion in Brave with my own local node without turning on Brave's local node. Having Brave's local node disabled turns off the "Toggle all IPFS integrations" toggle in IPFS Companion's settings. Trying to turn it on just redirects to Brave's settings, with a notification telling the user to turn on Brave's local node.

**Describe the solution you'd like**
Allow the "Toggle all IPFS integrations" toggle to be enabled with Brave's local node and only direct the user to enable Brave's node when IPFS Node Type is set to Provided by Brave.

**Comment by lidel** [comment]
Closing, as it is already allowed.

You can switch IPFS Companion to _External_ node (eg. provided by ipfs-desktop or go-ipfs) in Preferences (:gear: ):

> ![2021-09-24_15-25](https://user-images.githubusercontent.com/157609/134682068-fdb905ce-95a7-42b7-857a-1bdbe4348f63.png)

Make sure API and Gateway ports point at correct node (default in ipfs-desktop is 8080 and 5001):

> ![2021-09-24_15-29](https://user-images.githubusercontent.com/157609/134682540-74015026-ae7e-4928-b263-7f21b4caf6b4.png)
> ![2021-09-24_15-28_1](https://user-images.githubusercontent.com/157609/134682561-7437501a-5863-474d-99f0-e9b43f6908ea.png)


Then, you can disable node in Brave and make it use your local _Gateway_: 

>  ![2021-09-24_15-28](https://user-images.githubusercontent.com/157609/134682404-fa25b2d4-bf33-4f66-890f-0aa9deaf8931.png)

IPFS Companion will redirect things to local gateway running outside of Brave.

Afaik the only downside is that you won't see `ipfs://` in address bar (but this is only a cosmetic difference).
