### ISSUE TITLE
IPFS Companion doesn't work while NordVPN is active 

### ISSUE THREAD

**Issue by viktaur** [ipfs/ipfs-companion#1023]
**Describe the bug**
IPFS Companion doesn't work while NordVPN is active and slows down Brave browser a lot

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.29.76 Chromium: 93.0.4577.58 (Official Build) (64-bit)

**Additional context**
I've tried to change the server or protocol, but the problem persists. If I disable the VPN connection, everything works properly.

**Comment by lidel** [comment]
This is not related to Companion. It is either go-ipfs or an issue with a third party VPN service.
Let's continue on discussion forums: https://discuss.ipfs.io/t/ipfs-companion-doesnt-work-while-nordvpn-is-active/12106
