### ISSUE TITLE
[Firefox] HTTPS Only Mode redirects to https://ipfs-cid.ipfs.localhost/

### ISSUE THREAD

**Issue by da2x** [ipfs/ipfs-companion#1026]
**To Reproduce**
1. Enable `Use Subdomains` in IPFS Companion.
2. Enable `Enable HTTPS-Only Mode in all windows`. (Bottom of Settings: Security.)
3. Go to https://ipfs.io/

**Expected behavior**
Should redirect to `http://docs.ipfs.io.ipns.localhost:8080/`. Firefox *may* show an interstitial asking you to confirm navigation to an unencrypted website.

**Actual behavior**
IPFS redirects to `https://docs.ipfs.io.ipns.localhost:8080/`. The request times out. Firefox never suggests downgrading to HTTP because the browser explicitly navigates directly to HTTPS. (It only prompts when the browser intervenes and attempts to redirect to HTTPS.)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 92

**Comment by lidel** [comment]
@da2x I was unable to replicate this in Firefox 92.0.1 on Linux. 

- Do you have any other extensions installed that could do this? (eg. https://www.eff.org/https-everywhere)?
- Does the problem go away when you disable HTTPS-Only mode or add an exeption for `docs.ipfs.io.ipns.localhost:8080`, as described [here](https://support.mozilla.org/en-US/kb/https-only-prefs#w_turn-off-https-only-mode-for-certain-sites)?

**Comment by da2x** [comment]
> Do you have any other extensions installed that could do this?

No. Reproduces for me with a clean profile, just those two settings, and the IPFS companion.

> Does the problem go away when you disable HTTPS-Only mode

Yes.

>  or add an exeption for docs.ipfs.io.ipns.localhost:8080, as described here?

The exception thing doesn’t show (indicating that the URL was opened to https: directly instead of being redirected from http: to https:.). I can’t reproduce on Windows, but it reproduces on macOS and Fedora.
