### ISSUE TITLE
pin list loader and exporter

### ISSUE THREAD

**Issue by mikeal** [ipfs/ipfs-companion#1033]
It would be cool if we made it really easy for people to share their pinlists with each other. Some kind of feature for loading, updating and exporting pin lists would go a long way.

It would make it easy for people in the community to back up Web3 data when peolle post them on social media like https://twitter.com/artnome/status/1459310362935898122?s=21

**Comment by lidel** [comment]
Our GUI apps do not support low-level pins as those have no human-readable labels – we removed them actually :)) https://github.com/ipfs/ipfs-webui/issues/1773 

The current  story is that GUI users leverage MFS for keeping content around and protecting it from GC.
We have CAR import/export planned for webui https://github.com/ipfs/ipfs-webui/issues/1798

We won't be adding low level pins any time soon to GUIs – it could happen after we add human-readable labels to `ipfs pin`  (we already have them in `ipfs pin remote *` commands)
