### ISSUE TITLE
DNSLink chaining not resolving properly

### ISSUE THREAD

**Issue by jakehemmerle** [ipfs/ipfs-companion#1039]
### What we did

I assume the extension is using this lib under the hood. IPFS Browser extension 0.11.0. The URL in browser (Brave) is ipns://wiki.polkadot.network , and I was also able to reproduce the error using a HTTP gateway (https://ipfs.w3f.community/ipns/wiki.polkadot.network).

### Error

`ipfs resolve -r /ipns/wiki.polkadot.network: could not resolve name: "wiki.polkadot.network" is missing a DNSLink record (https://docs.ipfs.io/concepts/dnslink/)`

### Expected behavior

`browser -> _dnslink.wiki.polkadot.network -> _dnslink.polkadot-wiki.w3f.services -> resolve the wiki's hash`

### DNS TXT values
```
❯ dig +short TXT _dnslink.wiki.polkadot.network
"dnslink=/dnslink/polkadot-wiki.w3f.services"
                                                                                      
❯ dig +short TXT _dnslink.polkadot-wiki.w3f.services    
"dnslink=/ipfs/QmdncfsVm2h5Kqq9hPmU7oAVX2zTSVP3L869tgTbPYnsha"
```

Any misconfigurations on our part? Pretty sure we're doing it exactly how its described [here](ipns://dnslink.dev/#dnslink-chaining). @ironoa

**Comment by DannyS03** [comment]
Hello, seems like the issue still needs to be triaged, thanks
