### ISSUE TITLE
Addon interferes with localhost:8080 traffic in unexpected ways

### ISSUE THREAD

**Issue by tennox** [ipfs/ipfs-companion#1047]
**Describe the bug**
I was debugging an (alleged, not reproducible) [vuepress bug](https://github.com/vuepress/vuepress-next/issues/640#issuecomment-1015933274) for some hours, which resulted in the realisation that the bug would only appear while the IPFS companion addon was enabled in my browser. :sweat_smile: 

**To Reproduce**
I'm really not sure how to properly reproduce this behaviour :disappointed: - but maybe...
1. `git clone https://github.com/tennox/vuepress-root-bug-repro demo && cd demo && yarn`
2. `yarn start`
3. Open http://localhost:8080 in a browser with this addon installed
4. See empty page
5. Check devtools network tab, see failing requests:
![Screenshot from 2022-01-19 00-57-25](https://user-images.githubusercontent.com/2084639/150037940-92bc9743-9b25-4625-a8c8-6c06127008e7.png)
6. copy the cURL for that request, execute it and see it works without problems || 404:
  `curl 'http://localhost:8080/@vite/client' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0' -H 'Accept: */*' -H 'Accept-Language: en-GB,en;q=0.7,de;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8080/' -H 'Sec-Fetch-Dest: script' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'`

**Expected behavior**
Not altering localhost:8080 traffic

**Desktop (please complete the following information):**
 - OS: elementary OS 5.1.7 Hera
 - Browser: Firefox developer 97.0b4 (64-bit)
 - Companion Version: 2.19.1

**Comment by lidel** [comment]
Your vue app runs on the port which is the default Gateway port in ipfs-companion, you can change it in settings:

![2022-03-28_20-46](https://user-images.githubusercontent.com/157609/160465797-5f50763b-74f4-4e5c-b005-d4ff5fb632c5.png)

**Comment by tennox** [comment]
I know that this is the case, and I'm well aware how to ~~fix~~ work around the issue - but I don't agree that this is not an issue, as it took me many hours to find out what is happening.
Using port 8080 is quite a common thing, and I would argue that very few people would expect the addon to interfere in such a subtle way (either don't modify or block or at least some warning in the console that the addon is interfering with the traffic would be 'solutions' for this issue)
