### ISSUE TITLE
Detecting the IPFS Companion extension on the user

### ISSUE THREAD

**Issue by altoidkind** [ipfs/ipfs-companion#1048]
**Is your request for an opportunity related to a problem? Please describe.**
I directly use IPFS to deliver content to my users, and I want users to download that content faster if the JS feature checks to see if they have IPFS Companion installed, and therefore can minimize the cost of downloading content by using local content downloads **instead of using gateways** like ipfs.io, cloudflare-ipfs.com and others. **This will also help other sites that use IPFS for fast content uploads**.

**Describe the solution you would like to get**.
I can suggest a superficial solution: Load a specific module into your browser, like the MetaMask crypto wallet does (see. https://ethereum.stackexchange.com/a/51356 or https://stackoverflow.com/a/14399123/16782022).

**Describe the alternatives you've considered**.
I don't see any other alternatives how to set that IPFS Companion is installed on the user.

**Additional context**.
No.

**Comment by Carson12345** [comment]
I would like to take this one :)

**Comment by lidel** [comment]
If you have DNSLink set up on your domain name, IPFS Companion will redirect and load your website from a local gateway.

Would you be willing to unpack what you mean by "download that content faster if the JS feature checks to see if they have IPFS Companion installed"?
