### ISSUE TITLE
Linkify experimental feature - demo page shows unlinked "should be linkified" text

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-companion#1050]
**Describe the bug**

**To Reproduce**
1. Go to the [linkify-demo page](https://ipfs.io/ipfs/bafybeidvtwx54qr44kidymvhfzefzxhgkieigwth6oswk75zhlzjdmunoy/linkify-demo.html)
2. Notice that "ipns://ipfs.git.sexy" is not linkified (see screenshot below)

**Expected behavior**

All links under "Should be linkified" should be linkified.

**Screenshots**
![image](https://user-images.githubusercontent.com/1173416/152041833-c4b3e449-17a0-4696-8919-26315c6f506f.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.1 (21C52)
 - Browser: Chrome 
 - Version: 97.0.4692.99 (Official Build) (arm64)

**Additional context**

One of two fixes:

1. "ipns://ipfs.git.sexy" should be linkified.
or
2. "ipns://ipfs.git.sexy" should not be listed under the "Should be linkified section"

**Comment by lidel** [comment]
Good catch! This is because that domain name is dead and no longer has a valid DNSLink:
https://ipfs.io/ipns/ipfs.git.sexy/

@SgtPooki  mind opening PR that replaces all uses of  `ipfs.git.sexy` with `en.wikipedia-on-ipfs.org`  ?
