### ISSUE TITLE
go-ipfs 0.12 interop

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-companion#1059]
Ref. https://github.com/ipfs/go-ipfs/releases/tag/v0.12.0

- [ ] check if our webui preload  logic is impacted by `refs local` change or not

**Comment by SgtPooki** [comment]
in companion, you have browser action icon.. you can open webui. the very first time you install ipfs-companion, if you do this, your node may not have webui in local cache, so it may take time to fetch the content locally. this is not a great UX experience.. there is a blank page for 30 seconds or so. (20Mb or so)

That check is using CIDs, and in 0.12 go-ipfs, the format of CIDs was changed returned by refs local command to be CIDv1. 

https://github.com/ipfs/ipfs-companion/blob/5ed967e8032e8cb65fd70792f142d76f4d1ae838/add-on/src/lib/precache.js#L48-L59

**Comment by SgtPooki** [comment]
This task is blocked by https://github.com/ipfs/ipfs-companion/pull/1054
