### ISSUE TITLE
IPFS-Companion shows offline, but I have IPFS-Desktop working

### ISSUE THREAD

**Issue by chadlupkes** [ipfs/ipfs-companion#1068]
**Describe the bug**
IPFS-Companion is offline, no matter what I do. I have tried restarting IPFS-Desktop, updating all software, etc.

**Expected behavior**
It was working perfectly until the last update.

**Screenshots**
![image](https://user-images.githubusercontent.com/2680342/159185462-35ff6a58-ec35-4845-8d6e-6eea6f85db6f.png)
![image](https://user-images.githubusercontent.com/2680342/159185465-8266ba07-d9bf-4165-bb7d-0da83b26a03c.png)
![image](https://user-images.githubusercontent.com/2680342/159185468-eacaf6d2-a939-4654-9df1-23a8b42f9ad5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome Version 99.0.4844.82 (Official Build) (64-bit)
 - Browser: Brave [Version 1.36.116 Chromium: 99.0.4844.74 (Official Build) (64-bit)](https://brave.com/latest/)
 - IPFS-Desktop Version: 0.20.2
 - IPFS-Companion Version: 2.19.1

**Additional context**

**Comment by lidel** [comment]
Thank you for reporting this.

This is a regression introduced by https://github.com/ipfs/ipfs-desktop/pull/1956.
We fixed it in go-ipfs in https://github.com/ipfs/go-ipfs/pull/8690 by always safelisting `127.0.0.1:<port>` (where port is RPC API at 5001) but go-ipfs 0.13 was not released yet.

I'll prepare a bugfix release of ipfs-desktop shortly.

**Comment by chadlupkes** [comment]
Fixed, works perfectly.  Thank you!
