### ISSUE TITLE
Determine next steps after UR results

### ISSUE THREAD

**Issue by meandavejustice** [ipfs/ipfs-companion#1098]
Need to define next actions required from the User Research (UR) done by @juliaxbow. @lidel says there is another issue covering this (https://github.com/ipfs/ipfs-companion/issues/1088).

**Comment by SgtPooki** [comment]
@meandavejustice do you mind filling out more info here?

**Comment by SgtPooki** [comment]
@lidel do you know what this is?

**Comment by SgtPooki** [comment]
This could probably be done inside of https://github.com/ipfs/ipfs-companion/issues/1088, we could close this as a duplicate.

**Comment by meandavejustice** [comment]
Hey @SgtPooki been working on non PL things, I'm good with using #1088 instead 👍
