### ISSUE TITLE
Notification toggle

### ISSUE THREAD

**Issue by Martinligabue** [ipfs/ipfs-companion#1104]
**Is your feature request related to a problem? Please describe.**
I find the notification of ipfs is online/offline very annoying.

**Describe the solution you'd like**
A toggle for the notifications

**Describe alternatives you've considered**
Browser doesn't allow to manage this setting

**Additional context**
N/A

**Comment by lidel** [comment]
Agree! We already track this in https://github.com/ipfs/ipfs-companion/issues/1091, let's continue there.

**Comment by Martinligabue** [comment]
Thanks, couldn't find it searching for it, I used different words, illl follow that discussion
