### ISSUE TITLE
Brave: webui does not load, blank screen

### ISSUE THREAD

**Issue by amplicity** [ipfs/ipfs-companion#1112]
**Describe the bug**
I removed IPFS companion from my browser, then re-added it. I also re-initialized my local ipfs daemon. While my IPFS companion shows I am connected and I can see a count of nodes in the icon, whenever I click 'My Node', I am shown to a white page with 404s in the console for a list of json files:
- app.json
- notify.json
- welcome.json
- status.json
- files.json
- explore.json
- peers.json
- settings.json

This happened after I removed IPFS companion, then re-added it to Brave. Before this, it was working okay.  It's also worth mentioning that my `.ipfs` directory was nowhere to be found when IPFS companion was working properly, and I do not use IPFS desktop. I'm not sure how/where IPFS companion was finding an IPFS daemon, so I reinstalled IPFS and can confirm my local daemon is now working correctly.

**To Reproduce**
Unknown. This is a combination of a seemingly-botched installation and not enough information on how to rectify it.

**Expected behavior**
The node will connect to its neighborhood and display that it's online, but 'my node' will be unaccessible and display 404 for the above-referenced jsons.

**Screenshots**
<img width="1191" alt="Screen Shot 2022-12-07 at 1 27 50 PM" src="https://user-images.githubusercontent.com/2263838/206265634-e3ba1af4-a0c8-4eac-a9d6-f7943c636d30.png">
<img width="50" alt="Screen Shot 2022-12-07 at 1 27 59 PM" src="https://user-images.githubusercontent.com/2263838/206265656-a4c78fb0-cc6c-45e6-a0f7-c575bb87dd43.png">
<img width="310" alt="Screen Shot 2022-12-07 at 1 28 13 PM" src="https://user-images.githubusercontent.com/2263838/206265715-0ef4b00d-bc55-4d2e-89b6-398a6d04916c.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave
 - Version: IPFS companion 0.16.0

**Comment by lidel** [comment]
@amplicity try toggling the below setting in Companion's Settings and let us know if ipfs-webui (interface behind "My Node") becomes accessible.

> ![2022-12-13_22-44](https://user-images.githubusercontent.com/157609/207450433-a9850e17-3524-4943-bd0c-a25b93672100.png)
> ![2022-12-13_22-43](https://user-images.githubusercontent.com/157609/207450441-c62d45a5-ddc5-4276-a70b-706fa66871f3.png)

**Comment by amplicity** [comment]
My apologies for the radio silence here -- going through a move. I'm going to try this out and I'll cycle back with more details addressing both comments above.

**Comment by lidel** [comment]
I assume this is no longer relevant, if you were still using Brave node, you may want to follow  https://blog.ipfs.tech/2024-brave-migration-guide/
