### ISSUE TITLE
Add metrics tracking notice to IPFS Companion

### ISSUE THREAD

**Issue by juliaxbow** [ipfs/ipfs-companion#1114]
Background:
Following efforts to track and obtain necessary metrics around IPFS usage, we must notify companion users about how data is being collected and used as well as easily allow for users to opt out of non-necessary metrics

**Proposed solution**
- One way to do this is to have a push notification in the companion extension. Chrome and Firefox have requirements for how these are formatted; see screen recording for proposal
- Pros: One-time alert that defaults to tracking user metrics; user would click on the alert or gear icon to go to preferences to update settings in preferences window. A push notification makes the change in how we collect metrics super visible.
- Cons: Users may have push notifications disabled through their browser. Push notifications are also generally found to be annoying

https://user-images.githubusercontent.com/58958327/207476491-33002444-5389-4c9b-a565-34cf820b9864.mov

**Alternative Solutions**

In all options, the actual toggles for cookie opt-ins/out live in preferences. The alternatives below describe methods of notifying the user. 

Description: Notification alert on gear icon for initial notice of cookie tracking. Clicking on this will bring the user to the user preferences, where they will see a section that allows them to update their cookie preferences. The notification will disappear after first click. 
![Gear Notification](https://user-images.githubusercontent.com/58958327/207475937-35cdf4b7-458a-44d4-b958-2af5d06e2ad5.png)

Description: Cookie link in extension window. Always include link at bottom of the extension window that will link to user preferences and allow the user to change cookie preferences. 
![IPFS Cookie](https://user-images.githubusercontent.com/58958327/207475934-19f9b07f-de84-4108-91e8-4dd3e3c834e8.png)

**Additional context**
- See https://github.com/ipfs/ipfs-gui/issues/105 for discussion around necessary metrics; language not yet formalized

**Comment by lidel** [comment]
EU people are way pass the cookie-popup fatigue. Whatever we do should minimize the annoyance.

- "Notification alert on gear icon" sounds good
- Alternative idea is to add notice about "Opt-out telemetry"  to the welcome screen that is presented after initial install.  Either at the bottom, or as an additional section on the right (above or below  videos): 
  > ![2022-12-18_23-53](https://user-images.githubusercontent.com/157609/208323612-d9b719ee-d00c-462e-83c3-e3c9bc6180da.png)
 
 
 If you want to re-open the welcome screen, click on the cube in the left top corner of the Companion's browser action menu.

**Comment by SgtPooki** [comment]
discussion with @lidel. We're going to close this as this is not the plan we're moving forward with. see https://pl-strflt.notion.site/Telemetry-2023Q1-b005d4f217f44db3986902c67d922cf4 for latest
