### ISSUE TITLE
IPFS companion doesn’t redirects requests if they are torrent's webseeds

### ISSUE THREAD

**Issue by hollownights** [ipfs/ipfs-companion#1139]
See webtorrent/webtorrent#2434

When an URL for a file on the IPFS network is served through a [public IPFS gateway](https://docs.ipfs.tech/concepts/ipfs-gateway/) and used as source in a video element, the [IPFS companion browser extension](https://github.com/ipfs/ipfs-companion) can rewrite the request so that it points to the localhost, like this:

> https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR → http://localhost:8080/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR → http://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi.ipfs.localhost:8080

Unfortunately, the same isn’t true when WebTorrent process a public IPFS gateway URL used as a webseed for a torrent. In this case, the companion extension (apparently) doesn’t see the request to rewrite it and WebTorrent just tries to load the file through the public gateway, which is less than ideal, specially for large files.

Proper behavior could help some websites to more easily bridge the gap between a centralized web and a fully decentralized one: they could host all the static files on an IPFS node and publish them using their own public IPFS gateway and then, for audio and video files, they could also use WebTorrent, with the IPFS URLs serving as webseeds.

To try out IPFS URLs as webseeds:

1) Install the [IPFS desktop](https://docs.ipfs.tech/install/ipfs-desktop/)
2) Install the [IPFS companion](https://docs.ipfs.tech/install/ipfs-companion/) on the browser you will use for testing; 
3) [Import a file](https://docs.ipfs.tech/basics/desktop-app/) (preferably a large file) to your local IPFS node; 
4) Create a torrent for that same file using instant.io or btorrent.xyz and get its magnet link;
5) Get a public IPFS gateway URL to that file using the [“Share link” option](https://docs.ipfs.tech/basics/desktop-app/#share-files);
6) Add that IPFS URL to the magnet link as a webseed by adding the parameter “ws=[URL]” to the magnet link (use “&” before/after it to add it to the magnet link);
7) Go and try to torrent it using the browser on which you installed the companion extension;
8) Now change the public IPFS gateway URL from the magnet link to the path-like localhost URL for the same file and try to torrent it again.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: Tried with 108.0

**Comment by lidel** [comment]
Unable to reproduce, `magnet:?xt=urn:btih:fe2422ff2f474a10a4f765b37317875f77ce87f6&dn=war.jpg&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&ws=https://ipfs.io/ipfs/QmaRHR7tEEmDpc8iFenYyNNpaKLn67hqT1NkuLZtALkLtn`  loaded via https://instant.io triggers webseed, and the request is correctly redirected and loaded from my local gateway:

> ![2023-01-29-164521_1141x875_scrot](https://user-images.githubusercontent.com/157609/215337920-9b0dcdd3-1886-40a4-adb8-fb72bfd41dd5.png)
