### ISSUE TITLE
Show a toast/notification if the url was loaded by companion

### ISSUE THREAD

**Issue by whizzzkid** [ipfs/ipfs-companion#1206]
**Is your feature request related to a problem? Please describe.**
When companion is enabled, the redirection happens silently, we would like to have an option to enable a notification if the current url is being loaded by companion.

**Describe the solution you'd like**
A toast might be too intrusive, a badge on the companion might be more easier from ux point of view.

**Comment by lidel** [comment]
(spring cleaning)

- The icon indicator idea seems to overlap with https://github.com/ipfs/ipfs-companion/issues/662
- The idea of  interstitial page that acts as a splash screen is tracked in https://github.com/ipfs/ipfs-companion/issues/727

Feel free to provide comments in above issues.
