### ISSUE TITLE
[Brave] Two menu items when importing text to IPFS

### ISSUE THREAD

**Issue by dennis-tra** [ipfs/ipfs-companion#1216]
**Describe the bug**

When importing text (arguably not a super relevant use case :D) I see two menu items.

**To Reproduce**
1. right click on selected text
2. see the two menu items

**Expected behavior**

There should only be one menu item

**Screenshots**

<img width="306" alt="image" src="https://github.com/ipfs/ipfs-companion/assets/11836793/3fa46fbf-96cf-423b-8034-964ab8c65ecd">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version:

**Additional context**

Could this be because of Braves' built-in node which I have installed alongside the companion beta?

**Comment by lidel** [comment]
No longer relevant, https://blog.ipfs.tech/2024-brave-migration-guide/
