### ISSUE TITLE
github.com/ipfs/kubo/* isn't clickable

### ISSUE THREAD

**Issue by bradcarnage** [ipfs/ipfs-companion#1249]
**Describe the bug**
when you search for documentation, and try to click on a github.com/ipfs/kubo/* link, IPFS companion or brave tries to redirect to an IPFS resolver, when in reality it should just load content from github.

**To Reproduce**
1. Go to duckduckgo.com
2. Search for "ipfs kubo github"
3. Click on ipfs/kubo.
4. See error about invalid CID

**Expected behavior**
Redirect to original URL when CID invalid, or give the user the option to stop redirecting this domain upon encountering an error

**Screenshots**
![image1](https://github.com/ipfs/ipfs-companion/assets/8689194/d2610ad2-c2c5-49a1-af3c-c84b05d63191)
![image2](https://github.com/ipfs/ipfs-companion/assets/8689194/1848843d-362b-4a00-a793-15ddfebdb0d4)

**Desktop Information:**
 - OS: Windows
 - Browser: Brave
 - Version: 1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit) 
 - kubo v0.21.0 brave

**Additional context**
This was a really cool bug when trying to look up documentation and error reports for IPFS kubo :)

This "bugfix" should really just be a policy re-write on how the browser chooses to redirect sites or show error messages.
Ideally IPFS companion or the browser would show the resolution error, and give the user an option to "go to original URL and never redirect <domainname> /ipfs/ links from this domain again"

Possibly, the browser would simply redirect back to the original page upon a resolution error, without notifying the user, if it's a valid and reachable page on the internet. Although, this may cause the edge-case problem where you have an erroneous redirect, without the user knowing why, when they were expecting to resolve /ipfs/ content from their own gateway.

It's funny how github.com/ipfs/kubo/* matches this criteria, isn't it?
Sort of like shooting yourself in the foot, almost.
![foot](https://s4745.pcdn.co/wp-content/uploads/2015/06/shot-foot.jpg)

**Comment by lidel** [comment]
Yes, this is a bug in Brave, already tracked in https://github.com/brave/brave-browser/issues/29078. Closing.
@bradcarnage if you could comment on the brave issue that will be very helpful. :pray:

FYI redirect setting in Brave is separate from the one in companion. Brave setting is opt-in.  If you disable redirect in Brave then you will still be able to rely on the redirect provided by ipfs-companion, and the `ipfs://kubo` bug should be gone. 

@whizzzkid fysa we've talked with Brave that ipfs-companion should have ability read IPFS-related settings, and also modify them. That API is wip (https://github.com/brave/brave-browser/issues/31199) but no ETA yet.  Once we have it, companion will be able to disable upstream redirects, ensuring only ones provided by itself are used.
