### ISSUE TITLE
display the number/percent of loaded resources in context menu

### ISSUE THREAD

**Issue by nick-owens-eero** [ipfs/ipfs-companion#1317]
**Is your feature request related to a problem? Please describe.**
when using the companion, and some resources are loaded from my gateway, it is not easy to know how many resources were loaded from it.

**Describe the solution you'd like**
the 'Current Tab' context menu should display X/Y and Z% of resources loaded from the gateway.

**Describe alternatives you've considered**
a user could use the browser inspector to find out the origin resources were loaded from, but that is cumbersome and doesn't summarize it easily.

**Additional context**

**Comment by lidel** [comment]
Thank you for submitting this idea.

Similar one is already tracked in https://github.com/ipfs/ipfs-companion/issues/662 so closing this one as duplicate, feel free to provide comments there. :pray:
