### ISSUE TITLE
Add support for chromium-based browsers

### ISSUE THREAD

**Issue by AlexBeLi** [ipfs/ipfs-companion#218]
Because ipfs-chrome-extension and ipfs-chrome-station don't support ipfs>=0.4.5.

**Comment by lidel** [comment]
This may require some additional work due to minor incompatibilities between WebExtensions and Chrome APIs:
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities
- There is also a polyfill for standarized APIs (which is a subset of APIs provided by Firefox): https://github.com/mozilla/webextension-polyfill
- Chrome does not support `async` / `await` yet (Firefox does and I plan to use it extensively)
  In general, chrome target would probably need some kind of transpilling


Firefox is my daily driver so this has a low priority right now.

If someone wants to invest time to add `npm run build-chrome` sooner, a PR would be much welcome 🙃

**Comment by mateon1** [comment]
I just fixed ipfs-chrome-station, but it might take a while for xicombd/ipfs-chrome-station#15 to get merged, and the extension updated.
For now, you can use https://github.com/mateon1/ipfs-chrome-station/tree/fix/ipfs-0.4.5
To do so, clone the repo and switch to branch `fix/ipfs-0.4.5`. Run `npm install` and `npm run build`. You can then load the `./build` folder in Chrome as an unpacked extension.

**Comment by diasdavid** [comment]
Following up https://github.com/ipfs/in-web-browsers/issues/54#issuecomment-300234021, we want to have this WebExtension serving both.

Is `Only one of browser_action, page_action can be specified in chrome (we use both)` the only thing missing?

**Comment by lidel** [comment]
I remember there were multiple errors about unsupported manifest keys, eg. [recently introduced](https://github.com/lidel/ipfs-firefox-addon/issues/164) `protocol_handlers`.  I've added them to first post. There is probably more.

This "write once, run everywhere" story provided by Mozilla does not pass reality check.
As soon as we use non-canonical API provided by Firefox, we are not Chrome-compatible. 
And as you can see there are discrepancies  even within APIs copied from Chrome.

I suspect we will end up with chunks of conditional code and dedicated manifest and build pipeline for each browser.

That being said, we can simplify stuff by merging "pageAction" back into "browserActions". 
One thing less to worry about.

**Comment by lidel** [comment]
FYI I'll do my best in diagnosing / mitigating compatibility issues in `chromium-compat` branch this week. 
Stay tuned.  👌

**Comment by lidel** [comment]
Quick update: [extensionizer](https://github.com/MetaMask/extensionizer) is not enough, as it is still callback-based.

Firefox introduced promise-based syntax and that functionality is provided by [webextension-polyfill](https://github.com/mozilla/webextension-polyfill).

**Comment by lidel** [comment]
Oh hey, look what the cat dragged in:

>  ![2017-05-13-211205_897x506_scrot](https://cloud.githubusercontent.com/assets/157609/26028465/39db17a0-3821-11e7-8d80-be552a3a198e.png)

I made some changes and it loads under Chromium without [Hard Errors](https://github.com/ipfs/ipfs-firefox-addon/issues/218#issuecomment-287620250).

So far I noticed 3 issues that need additional work (see ["Soft Errors"](https://github.com/ipfs/ipfs-firefox-addon/issues/218#issuecomment-287620250)), but basic functionality works (redirect, Quick Upload, copying public URL, pinning etc)

**Comment by styfle** [comment]
@lidel Is this published to the Chrome Web Store now?

**Comment by lidel** [comment]
Not yet, but thanks for asking! I created  #268 to track that.
