### ISSUE TITLE
Change the name before v2.0.0 released?

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-companion#225]
In past Firefox add-on was named _IPFS Gateway Redirect_. 

It is an understatement, because in addition to redirect functionality, [v2.0.0alpha2](https://github.com/lidel/ipfs-firefox-addon/releases/tag/v2.0.0alpha2)  features IPFS node status monitoring, experimental `dnslink` support,   `web+ipfs://` protocol support and `quick upload` options for local and web content. 

I feel it may be a good time to pick visually shorter and  more broad name. 

**Please vote** using emoji reaction below  **or suggest something more elegant in comments below** 
(one per comment, to make it easy to vote with 👍  reactions)  🙃 

> 
> 👍 here → change name to `IPFS Companion`
> 👎  here → keep the old name `IPFS Gateway Redirect`
> go to [this comment](#issuecomment-300201268) →  change name to `IPFS Station`
>

**Comment by lgierth** [comment]
Reasons for my change-vote:
- The gateway will hopefully soon be just one of various "transports"
- Redirect is an implementation detail

**Comment by lidel** [comment]
`IPFS Station` was suggested in https://github.com/ipfs/in-web-browsers/issues/54
(👍  this comment to vote for it)

**Comment by diasdavid** [comment]
Let's timebox this decision. I say, let's pick the name till Wednesday 17. That give everyone enough time to check this issue and vote

**Comment by lgierth** [comment]
Ping -- this timebox expires on Wednesday.

Station sounds good to me IF that means the current station tool and the addon will be one thing.

**Comment by diasdavid** [comment]
Thank you @lgierth ! :)

**Comment by diasdavid** [comment]
Sounds like `IPFS Gateway Redirect` it is 🍾

**Comment by lidel** [comment]
You mean... `IPFS Station` ? 🙃

**Comment by diasdavid** [comment]
Oh, I meant `IPFS Companion`

- `IPFS Companion` - 6 votes
- `IPFS Gateway Redirect` - 1 vote
- `IPFS Station` - 5 votes

![image](https://cloud.githubusercontent.com/assets/1211152/26309525/67a3eb66-3ecb-11e7-8509-627231e0df9c.png)

![image](https://cloud.githubusercontent.com/assets/1211152/26309531/6c2ba3ae-3ecb-11e7-88d7-afccd1bae702.png)

**Comment by lidel** [comment]
Oy... that was a close one 😕 
We've added "Station" after "Companion" already had 4 votes, and some votes are duplicated.

@lgierth, @RndFooBar, @verox, @jedahan, @mateon1, @sonatagreen:
Please check your votes,  decide between "Station" and Companion" and update your votes accordingly.
Make sure you vote only for _one option_.

**Comment by lidel** [comment]
Lol, seems that made `IPFS Companion` even stronger 🙃 
Can we say it is settled? What is the next step? Repo rename to `ipfs-companion`? Who can do it?

**Comment by VictorBjelkholm** [comment]
Renamed :) Welcome to `ipfs-companion`! :tada:

**Comment by VictorBjelkholm** [comment]
Screenshot for historic purposes:

![image](https://cloud.githubusercontent.com/assets/459764/26372094/03be69b8-3ffd-11e7-8d4e-6d767ce5697d.png)
