### ISSUE TITLE
Copypaste public gateway URL from location bar

### ISSUE THREAD

**Issue by sonatagreen** [ipfs/ipfs-companion#24]
I'm accustomed to copying URLs with Ctrl-L Ctrl-C. This gives me the custom gateway URL (http://localhost:8080/etcetera), rather than the public gateway URL (https://ipfs.io/etcetera).

If possible, it would be nice to be able to copy the public gateway URL from the location bar. Ideally, the location bar should still visually display the custom gateway URL (or, optionally, the canonical address), similarly to how it normally displays e.g. "example.com" but copies as "http://example.com/".

**Comment by lidel** [comment]
I use <kbd>ctrl+l</kbd>&<kbd>ctrl+c</kbd> too, good idea!  :+1:  

Of course the end result should be configurable:
- copy URL to public gateway
- copy canonical IPFS path
- do nothing, copy URL as is

I'll look into this in a spare moment (support in old/new Addon SDKs).  

For now you can a use [context menu](https://i.imgur.com/3KlHWHU.png) (under right click on a page loaded via custom gateway) items.

**Comment by lidel** [comment]
Two years later 👀  WebExtensions landed (see #20  for more details).

I revisited this issue and it is not possible to override <kbd>CTRL</kbd>+<kbd>C</kbd> in Location  Bar context.

What we can do, is to use [commands API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands) and define a new keyboard shortcut that will place public gateway URL in user's clipboard.
It would be one step, without the need for <kbd>CTRL</kbd>+<kbd>L</kbd> to focus Location Bar. 

I am thinking about <kbd>ALT</kbd>+<kbd>C</kbd> or <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>C</kbd>, 
but I need to check if it does not impact the way some diacritics are created (eg. "ć" in Polish).

**Comment by lidel** [comment]
I tried to address this, but it is not possible to implement it in WebExtension.

[MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard) states that:
> you can write to the clipboard like this in all execution contexts except background pages. **In Firefox you can't select text or focus an input field in background pages, so you can't write to the clipboard from a background page.**

This means the only working cross-browser and future-proof way to copy "canonical" and "public" URLs is via Browser Action button: 

> ![2017-07-22-170243_1721x1421_scrot](https://user-images.githubusercontent.com/157609/28492244-c9fb7e1e-6eff-11e7-953d-bd79abf622fd.png)
