### ISSUE TITLE
WebUI for non local machine does not work

### ISSUE THREAD

**Issue by dsvi** [ipfs/ipfs-companion#252]
for version 1.6
The WebUI menu loads the ipfs webui page. But the page itself assumes `localhost` as the api address. Could that be possible for the plugin to change the `localhost` in the page to Custum Gateway Host from the plugin settings?

**Comment by lidel** [comment]
Thank you for reporting this. 

Good news: providing alternative hostname for API port is [already addressed](https://github.com/ipfs/ipfs-companion/issues/249) in `2.x` versions:

> ![2017-05-17 08_24_12-add-ons manager](https://cloud.githubusercontent.com/assets/157609/26141057/3c64fe26-3ada-11e7-90c7-c4cf067a8f89.png)

It will take some time before we release 2.x.x as a stable version, but if you like to test experimental things  feel free to install latest "alpha" from Development Channel:

- https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/versions/beta

**Comment by dsvi** [comment]
you probably didn't understand the problem. its not in a separate config, it's in the fact that WebUI page (at QmPhnvn747LqwPYMJmQVorMaGbMSgA7mRRoyyZYz3DoZRQ) has hardcoded `localhost` in it. so no matter what you have configured, it still tries to connect to localhost.

**Comment by dsvi** [comment]
you didn't get the point. the problem is not in a separate config, tha problem is in the fact, that WebUI page has `localhost` hardcoded in it. So no matter what you are using in config, it still tries to connect to localhost.

**Comment by lidel** [comment]
Ah, indeed! My apologies.

Just to be clear, all this add-on does when you click "Open WebUI" is to open [`<IPFS API URL>/webui`](https://github.com/ipfs/ipfs-companion/blob/176325af8c8fc136c15e5bf6bf5623bf389386cd/add-on/src/popup/browser-action.js#L212-L214) in a new tab.  That's it.

WebUI is developed as a separate project and if it has a bug or usability issue it should to be reported upstream.  Please create a new issue at https://github.com/ipfs/webui/issues 
(It is the only way to fix this in a future-proof way, hacking WebUI from WebExtension is not robust enough)

PS. If you need a workaround that "just works right now", try ssh tunnel method described in https://github.com/ipfs/webui/issues/95#issuecomment-250007361

**Comment by dsvi** [comment]
I see. thanks for the links! I'll report it there.
