### ISSUE TITLE
Rewrite the host to ipfs://?

### ISSUE THREAD

**Issue by skorokithakis** [ipfs/ipfs-companion#253]
The current `http://127.0.0.1/ipfs/<id>` address is a bit ugly, would it be possible/desired to rewrite those links to `ipfs://<id>`?

**Comment by lidel** [comment]
It was possible to keep `fs:/ipfs/<id>` in address bar with old SDK, but there are no WebExtension APIs for that.. yet.

Status of  "custom protocol support" is tracked in #164, feel free to subscribe to it if you want to get updates about that effort.
