### ISSUE TITLE
Isn't showed checkboxes in Preferences

### ISSUE THREAD

**Issue by AlexBeLi** [ipfs/ipfs-companion#257]
Opposite by the "Enable dnslink lookups for every website".
Or maybe i understood anything wrong?
Firefox 55 (2017.05.31); IPFS Companion 2.0.0alpha5
![ipfs companion](https://cloud.githubusercontent.com/assets/20776735/26646283/6f4b504e-4654-11e7-8bcb-1361cfa42051.png)

**Comment by lidel** [comment]
Thank you for reporting this! 
There is indeed a regression under FF55, I'll look into it.

PS. Feedback like this is very much appreciated, as we do not have robust test suite yet (#145, #165).

**Comment by lidel** [comment]
Please try [v2.0.0alpha6](https://github.com/ipfs/ipfs-companion/releases/tag/v2.0.0alpha6).
