### ISSUE TITLE
Toolbar icon flickers ON after installing despite no daemon running

### ISSUE THREAD

**Issue by machawk1** [ipfs/ipfs-companion#263]
This is a subtle UI issue that I noticed when first testing out the add-on. The exhibited behavior is that the add-on flickers the ON badge when it's first installed regardless of the state of the daemon. After a few seconds (where I presumed the state of the daemon is checked), the badge displays the correct OFF badge. Attached is a GIF of this behavior.

* IPFS Companion v. 1.6.0, installed from [Mozilla Add-Ons](https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/)
* go-ipfs v. 0.4.10
* Mozilla Firefox v. 53.0.3 (64-bit) for macOS 10.12.5

![companionflicker](https://user-images.githubusercontent.com/2514780/27921349-7c268ce0-6245-11e7-9c98-79d20274c08a.gif)

**Comment by lidel** [comment]
Thank you for reporting this!

This is fixed in WebExtension version (`2.x`) – if you enjoy living on bleeding edge, give it a try! 
It is currently in beta, but can be manually installed from Developer Channel:
* https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/versions/beta

**Comment by machawk1** [comment]
@lidel Thanks! I installed it from the dev channel and cannot replicate the issue.
