### ISSUE TITLE
Publish to Chrome Web Store

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-companion#268]
Browser extension is published to Firefox [AMO](http://addons.mozilla.org) (WebExtension version is awaiting review). 
Now that #218 is closed we probably want to do the same for Chromium based browsers.

AMO supports ownerhsip sharing, meaning multiple people can manage extension page, upload new versions etc. This makes it future-proof in case anything happens to me.

Unfortunately it is not possible to share ownership on [Chrome Web Store](https://chrome.google.com/webstore/category/extensions).  
Google  [suggests using a new account just for your app instead of your personal account](https://developer.chrome.com/webstore/publish#create-a-developer-account).

So the plan is:

- [x] create Developer Account at Google (https://chrome.google.com/webstore/developer/dashboard)
  - [ ] share credentials with @diasdavid (ownership fail-safe)
- [x] publish extension
  - [x] upload `v2.0.8` to Chrome Web Store as _Unlisted_
  - [x] create listing (screenshots etc)
  - [x] pass review 
  - [x] make _Public_

@ipfs/admin, any thoughts on this? Is it okay to proceed?

**Comment by lgierth** [comment]
@lidel awesome, sounds good

**Comment by diasdavid** [comment]
@lidel let's do it :)

**Comment by lidel** [comment]
I submitted it as "unlisted" for now, to test the process:

>  ![2017-08-13-210605_305x102_scrot](https://user-images.githubusercontent.com/157609/29252661-69dd0750-806b-11e7-9a6e-1f20a5b0a9b2.png)

But it got flagged by automated tools and is "pending manual review":

>  ![2017-08-13-210812_589x205_scrot](https://user-images.githubusercontent.com/157609/29252666-89f83ef6-806b-11e7-82fc-be0799ec42f3.png)

Let's wait for the result of manual review 🤔

**Comment by lidel** [comment]
Unlisted extension is available [here](https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch) but it does not work correctly. 

It seems non-developer extensions triggers some kind of additional validation and Chromium 59 refuses to run it due to `unsafe-eval`: 

> 
![2017-08-15-154938_924x286_scrot](https://user-images.githubusercontent.com/157609/29318663-61973018-81d1-11e7-9953-3929a3317b17.png)

Begs the question: how does "manual review" looks like at Google, if they did not catch big error on initial extension load of extension? 🙃

Efforts to solve `unsafe-eval` are already tracked in https://github.com/ipfs/ipfs-companion/issues/269

**Comment by lidel** [comment]
It is now possible to do one click install from Chrome Web Store 🎉 🎊
- https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch

If anyone is using Chrome or Chromium: **please give it a try**.  I don't have Google Chrome at hand, but smoke tested it under Chromium 59 and functionally it seems to work as expected (apart from the lack of protocol handlers – https://github.com/ipfs/ipfs-companion/issues/164).
