### ISSUE TITLE
Remove use of unsafe-eval

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-companion#269]
We allowed `unsafe-eval` in browser extension because  browserified bundle `ipfs-api.min.js` relies on `eval`. Unfortunately Mozilla does not accept extensions with `unsafe-eval`:

> The use of &#39;unsafe-eval&#39; is not allowed in the manifest.json&#39;s CSP as it can cause major security issues. [feedback from review]

> [..] extensions with 'unsafe-eval', 'unsafe-inline', remote script, or remote sources in their CSP are not allowed for extensions listed on addons.mozilla.org due to major security issues.  [[MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_security_policy)]

We need to address it somehow.

Any ideas @ipfs/javascript-team? 
Is it possible to create own bundle without `eval`?
We can start using webpack if needed.

**Comment by styfle** [comment]
Can you link to the code that is doing the `eval`? And what is it evaluating?

**Comment by diasdavid** [comment]
searching for `eval` on the min file reveals that is something that Webpack injects as part of its bundling:

![image](https://user-images.githubusercontent.com/1211152/28731115-7275f336-7387-11e7-99fb-a2b522acb164.png)

Which gets in because of the `script` loader https://github.com/webpack/webpack/issues/4899

Investigating how to disable it (it's not actually present in our config file https://github.com/ipfs/aegir/blob/master/config/webpack.js)

**Comment by yfdyh000** [comment]
https://github.com/substack/vm-browserify/blob/bfd7c5f59edec856dc7efe0b77a4f6b2fa20f226/example/run/bundle.js#L430

**Comment by lidel** [comment]
FYSA we need to resolve this two-three weeks before [Firefox 57 is released](https://wiki.mozilla.org/RapidRelease/Calendar), otherwise users will be left dry without working browser extension :(

**Comment by dignifiedquire** [comment]
I do not think the issue is the `script-loader`, I searched through all deps and it does not get installed and still `eval` is present in the built file.

**Comment by dignifiedquire** [comment]
I believe I found the offender. The shim for [`vm`](https://nodejs.org/api/vm.html) relies on `eval`, and it seems this is used in the dependency `asn1`.

**Comment by dignifiedquire** [comment]
Here: https://github.com/indutny/asn1.js/blob/master/lib/asn1/api.js#L21 to be exacdt

**Comment by diasdavid** [comment]
Need to think more about this, but I'm guessing that we can get rid of this https://github.com/substack/vm-browserify/blob/master/index.js#L105

**Comment by dignifiedquire** [comment]
Looking at this [PR](https://github.com/indutny/asn1.js/pull/38) it seems that things should work, it will try to use the `eval` and fail due to csp but still work. @lidel is the issue that any warning with eval will be rejected, or did you actually experienced failures because of the csp restrictions?

**Comment by lidel** [comment]
Mozilla rejected our submission due to `unsafe-eval` in our CSP:

https://github.com/ipfs/ipfs-companion/blob/bbeaddeedf1a4781cd0dd40ba822911ee16269c9/add-on/manifest.json#L78

They *may*  not care if `eval` is in minified file  as long as `unsafe-eval` is removed from CSP.

Which I can't do because `ipfs-api` (v14.0.4)  does not work in WebExtension context without it. 

It fails to load under both Firefox and Chrome:

> ![2017-08-16-170832_826x160_scrot](https://user-images.githubusercontent.com/157609/29370427-92d65044-82a5-11e7-9a9f-422a2eaaf22b.png)


> 
![2017-08-15-154938_924x286_scrot](https://user-images.githubusercontent.com/157609/29370095-b45073d6-82a4-11e7-902c-6f482e77b3c5.png)

**Comment by dignifiedquire** [comment]
@lidel @diasdavid I have an experimental build which should improve things, could you try this out and let me know if it helps? (based on `master` if js-ipfs-api)
[dist.zip](https://github.com/ipfs/ipfs-companion/files/1250084/dist.zip)

**Comment by lidel** [comment]
@dignifiedquire  I replaced `ipfs-api.min.js` with `index.js` from your .zip and retested under Chrome/Firefox, both fail due to CSP:

> ![2017-08-25-005311_690x306_scrot](https://user-images.githubusercontent.com/157609/29692450-5c1edbd4-8930-11e7-9818-1fe0ea1629b0.png)

Seems that `src` String  causes `Function.apply` to fail due to CSP:

> ![2017-08-25-005424_525x239_scrot](https://user-images.githubusercontent.com/157609/29692452-6066f7f8-8930-11e7-9971-3c59bf8ef067.png)

**Comment by diasdavid** [comment]
@lidel you never had issues with `connect-src` on the CSP since you always dial to a localhost node, right?

If we were to try #248, [we would need to figure out `connect-src` as it would block dials to WebSocket nodes](https://github.com/brave/browser-laptop/issues/10683).

**Comment by lidel** [comment]
@diasdavid correct, `localhost` and HTTP-only (no WSS), so there were no issues.

**Comment by diasdavid** [comment]
@lidel @dignifiedquire what's the status here, any other ideas?

**Comment by lidel** [comment]
No _good_ ideas on my end, just status update:

Firefox release is blocked due to `unsafe-eval` in `manifest.json/content_security_policy` 
The `eval` seems to be required by both `js-ipfs-api` and `is-ipfs`. Both are built by [AEgir](https://github.com/dignifiedquire/aegir). 

The best case would be to find an upstream  fix: the problem is not limited to this extension, as you've seen in  https://github.com/diasdavid/browser-laptop/pull/1#pullrequestreview-59048553 use of  `eval` always causes weird looks. If we could remove its use completely, that would solve us headache across all projects. 

There is a possibility we could find a workaround and sandbox `eval`, somehow.
I did some research at https://discourse.mozilla.org/c/add-ons, but found no working solution. 
I've seen some [iframe-based sandboxing attempts](https://discourse.mozilla.org/t/webextension-sandboxing-eval/13659/3?u=lidel), but as far I can read into them, they still require `unsafe-eval` and/or `unsafe-inline`.

**Comment by dignifiedquire** [comment]
Update: Found out the `Function.apply` is from generator-function, which is a dependency of https://github.com/mafintosh/protocol-buffers which we use for protobuf support. Currently working on removing the use of that library.

**Comment by dignifiedquire** [comment]
Step 1: https://github.com/ipfs/js-ipfs-unixfs/pull/18

**Comment by dignifiedquire** [comment]
Step 2: https://github.com/ipld/js-ipld-dag-pb/compare/fix/proto?expand=1

**Comment by dignifiedquire** [comment]
Step 3: https://github.com/libp2p/js-libp2p-crypto/pull/107

**Comment by dignifiedquire** [comment]
@lidel build without protocol-buffers lib and no `Function.apply` [dist 2.zip](https://github.com/ipfs/ipfs-companion/files/1275640/dist.2.zip). Want to give it another spin?

**Comment by lidel** [comment]
@dignifiedquire this version works without `unsafe-eval` in `manifest.json`, extension loaded and functionality seems to work fine 👍  🎉 

FYI there  was one CSP error:

> 
![2017-09-05-072907_722x138_scrot](https://user-images.githubusercontent.com/157609/30046605-605dfe7a-920c-11e7-8cef-31a16079dc3a.png)


it was triggered by this line of `dist/index.js`:

```javascript
var mod = eval("quire".replace(/^/,"re"))(moduleName); // eslint-disable-line no-eval
```

but from what I was able to check it does not impact anything we use in browser extension.
Is this `eval` something we need to have? 

As long as we don't have t `unsafe-eval` in `manifest.json` it should pass the review at Mozilla, but if we can eliminate all uses of `eval` that would remove CSP errors from Browser Console.

**Comment by dignifiedquire** [comment]
Great to hear that @lidel. That eval is coming from our new protobuf library: https://github.com/dcodeIO/protobuf.js/issues/593 but should hopefully resolved soonish.

**Comment by dignifiedquire** [comment]
@lidel latest release of js-ipfs-api should be free of eval, hopefully. Please give it another try :)

**Comment by lidel** [comment]
@dignifiedquire The latest one at npmjs.com is `ipfs-api@14.3.3` and it still produces error due to `Function.apply`. I re-tested version from [dist 2.zip](https://github.com/ipfs/ipfs-companion/files/1275640/dist.2.zip) and it still works fine. 

I guess either you did not publish the latest version yet or there is some kind of regression since `dist 2.zip`

**Comment by diasdavid** [comment]
@lidel I was lucky with js-ipfs, you might have to do a fresh npm install and fresh npm run build with ipfs-api.

**Comment by lidel** [comment]
Just to eliminate possibility of me going insane 🙃  

This:
```bash
curl -s https://unpkg.com/ipfs-api@14.3.3/dist/index.js | grep -B 10 Function.apply 
```
returns:
```javascript
var src = 'return ('+line.toString()+')'

    var keys = Object.keys(scope || {}).map(function(key) {
      return key
    })

    var vals = keys.map(function(key) {
      return scope[key]
    })

    return Function.apply(null, keys.concat(src)).apply(null, vals)
```

..right?

**Comment by dignifiedquire** [comment]
Seems something went wrong in the release, unpkg version shows Function.apply but when I build on master with fresh deps it the apply is gone

**Comment by diasdavid** [comment]
One more time 🎶

![image](https://user-images.githubusercontent.com/1211152/30183505-90f3933a-9412-11e7-8b27-3a43993eb945.png)

**Comment by lidel** [comment]
`ipfs-api@14.3.4` works indeed! 🚀

**Comment by dignifiedquire** [comment]
> ipfs-api@14.3.4 works indeed! 🚀

AWESOME 🎉
