### ISSUE TITLE
Firefox 55 warns extension is “Legacy”

### ISSUE THREAD

**Issue by da2x** [ipfs/ipfs-companion#270]
Version 1.6.0 as published in the Firefox Extension Catalog will stop working in Firefox 57 (due 2017-11-14). The extension is identified by Firefox as using the legacy add-on API and not the new WebExtensions API.

**Comment by lidel** [comment]
Thank you for reporting this warning.
It is noted and we are doubling down on migration.

(Closing as a duplicate of #20, where we track Migration to WebExtensions API)
