### ISSUE TITLE
Add quick toggle for gateway redirect/all functionality

### ISSUE THREAD

**Issue by mateon1** [ipfs/ipfs-companion#274]
Do something similar to IPFS Station (chrome extension), and include a toggle for gateway redirect in the main interface.
Possibly add a way to temporarily toggle all functionality of the extension (globally and/or per site), similar to how ublock does it.

I find that I spend a lot of time going to the extensions page and manually disabling and then re-enabling the extension when I want to cache a hash on a public gateway.

**Comment by lidel** [comment]
I think this is addressed in [latest v2.x.x from Developer Channel](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/versions/beta). 

Give it a try:

If you disable automatic mode in Preferences:
>  ![2017-09-04-015514_427x37_scrot](https://user-images.githubusercontent.com/157609/30007658-49b7ce56-9114-11e7-9d9b-b49642ee55a4.png)

then you should  be able to manually toggle redirect:
>  ![2017-09-04-015542_1720x1421_scrot](https://user-images.githubusercontent.com/157609/30007659-4fd5142e-9114-11e7-96be-01e171f26cf2.png)

You can also enable/disable redirect per site by adding/removing its hostname:

>  ![2017-09-04-015948_514x47_scrot](https://user-images.githubusercontent.com/157609/30007677-be42a246-9114-11e7-90b6-1decea0c87ea.png)

Feel free to reopen if you had something different in mind.

**Comment by mateon1** [comment]
Yeah, I had a button like that in mind, and I didn't see this option due to automatic mode, but I think it should still be available even in automatic mode. Note that I cannot reopen this issue.

The Public Gateways Hosts setting could be better explained in the extension settings as well, the name isn't self-explanatory when it comes to what the option does.

**Comment by lidel** [comment]
Good points. 

 I see should could improve UX around it, perhaps something like this:

- improve description of "public gateways hosts" 
- change browser action menu to always have item to "toggle redirect"
  - "automatic mode" would be disabled when user manually toggles redirect 
     (user would have to to re-enable it in preferences) 

Does this take on UX sound good? Or maybe there is a simpler way to handle this?

**Comment by mateon1** [comment]
Hm, I'm not sure that disabling automatic mode once the user toggles the gateway redirect setting is a good idea. My thoughts on this:

The extension (always) provides a "Disable/enable gateway redirect" button. When a user clicks on that button, the extension temporarily stops redirecting requests for IPFS resources.
Toggling gateway redirect twice should not cause any change in the configuration state/settings of the program. Imagine the gateway caching scenario in the first comment: The user disables redirect and makes a request to ipfs.io/ipfs/..., once the resource loads, the user re-enables redirect. It would be confusing if "automatic mode" was disabled after doing this.

I also believe that automatic mode should be on by default, but configurable as the common case is to only redirect if the user's IPFS daemon is online (the user expects things to "just work"), while rarely, some users might have weird setups that might not work well with /api/swarm/peers requests. This is a bit off topic, but it demonstrates that changing the setting is rarely what people would want when disabling redirect.

Improving descriptions of settings with a (?) icon with a tooltip for most settings might be a good idea.

**Comment by lidel** [comment]
FYI updated Preferences screen will look like this:

![2017-09-10-201017_918x1213_scrot](https://user-images.githubusercontent.com/157609/30251663-89428c6e-9664-11e7-9630-bcdf6ea6db13.png)
