### ISSUE TITLE
Doesn't seem to redirect CIDv1

### ISSUE THREAD

**Issue by djdv** [ipfs/ipfs-companion#275]
Using version 2.0.0alpha7

Only the first hash(CIDv0) is anchored and redirected, the other 2(CIDv1) are not, sometimes the other hashes are anchored but only if they're not the first hash and not broken with a line, they're never redirected though.
`ipfs add hello.txt`
/ipfs/QmcTkUnEKwnnodaCRSVFpFEJTMJNcFfU64cD6s3BxfbWvf
`ipfs add --cid-version=1 hello.txt`
/ipfs/zb2rhkWWWwy77qJ1n4ghAnFktRkJT66psfWqGjvQ3bc3W2U8r
`ipfs add --chunker=rabin --cid-version=1 --hash=Blake2b-256 hello.txt`
/ipfs/zCT5htke6LPUaHfrtDJkv15EekGG8xnY3eHE52ZbnBphinybqchC

/ipfs/zCT5htke6LPUaHfrtDJkv15EekGG8xnY3eHE52ZbnBphinybqchC
^not anchored
/ipfs/QmcTkUnEKwnnodaCRSVFpFEJTMJNcFfU64cD6s3BxfbWvf
/ipfs/zCT5htke6LPUaHfrtDJkv15EekGG8xnY3eHE52ZbnBphinybqchC
^anchored

![companion-addon-bug01](https://user-images.githubusercontent.com/13862850/30034160-7877d2fa-916d-11e7-8c44-2638821f57e3.png)

**Comment by lidel** [comment]
Thank you for reporting this!

IPFS resources are detected by`is-ipfs` library, which seems to be lacking support for CIDv1.
I created https://github.com/fbaiodias/is-ipfs/issues/12 to address that. 

Let's keep this issue open until the upstream fix is released.

**Comment by lidel** [comment]
@djdv I've just published above fixed as `v2.0.9beta1` to [Developer Channel](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/versions/beta), give it a try! ✨
