### ISSUE TITLE
make ipfs://ANYHASH point to http://127.0.0.1:PORT/ipfs/ANYHASH

### ISSUE THREAD

**Issue by gustavohmsilva** [ipfs/ipfs-companion#278]
Hi everyone. This is a feature I would love to have on the companion, but I think it is still not implemented. Is is possible to do this, does the Firefox SDK accept such invasive alteration? If so, could this be added to a project milestone?

**Comment by lidel** [comment]
Good news: this is work-in-progress!
It is something that we had working in legacy SDK, but is not fully addressed by WebExtension APIs.. yet.

We track this exact thing in #164, so I am closing this one 👍

**Comment by gustavohmsilva** [comment]
Thanks for the info lidel!

**Comment by lidel** [comment]
FYI this feature landed in [v2.0.11](https://github.com/ipfs/ipfs-companion/releases/tag/v2.0.11) 🚀
