### ISSUE TITLE
Option to disable daemon online/offline notifications

### ISSUE THREAD

**Issue by Stebalien** [ipfs/ipfs-companion#282]
Personally, I don't really want to be told when my daemon comes online or goes offline. Unfortunately, I can't find a setting for disabling this notification.

Note, I'm using the webext beta: 2.0.9beta1.

**Comment by lidel** [comment]
Good idea, added to the TODO list!

**Comment by lidel** [comment]
@Stebalien I've just released [v2.0.10](https://github.com/ipfs/ipfs-companion/releases/tag/v2.0.10) with option to supress notifications:
> ![2017-09-28-005802_543x80_scrot](https://user-images.githubusercontent.com/157609/30942267-4c9d1ad4-a3ea-11e7-8c39-98a660b0cff9.png)

(one can still inspect Browser Console / background.html -- notifications are logged into console there)
