### ISSUE TITLE
How to handle Public Writable Gateways in browser extension?

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-companion#285]
Something I've noticed at [discuss.ipfs.io](https://discuss.ipfs.io/t/is-there-any-public-writable-gateway/1140/4?u=lidel):

> So, seems that https://www.eternum.io (which http://ipfessay.stavros.io is using) is writable

Loading the site (which utilizes writable gateway) with ipfs-companion is problematic: 

1. http://ipfessay.stavros.io redirects to https://www.eternum.io/ipns/QmSWnBwMKZ28tcgMFdihD8XS7p6QzdRSGf71cCybaETSsU/

2. ipfs-companion redirects that to my local gateway http://127.0.0.1:8080/ipns/QmSWnBwMKZ28tcgMFdihD8XS7p6QzdRSGf71cCybaETSsU/

3. Clicking on publish does nothing, because my local gateway is read-only and rejects HTTP `PUT`:

   > ![2017-09-29-180102_995x29_scrot](https://user-images.githubusercontent.com/157609/31024687-2d8f9b4c-a540-11e7-9551-d6f941c022ea.png)

Ouch. That is a bad UX.

I see two ways to "fix" it:

**(A)** Display a popup informing user that request failed because custom gateway is read-only and leave it up to users to either: **(A1)** decide to make local gateway writable **(A2)** temporarily  disable redirect to custom gateway and use original one
**(B)** Disable "gateway redirect" for HTTP  `PUT` and `POST` and always use original gateway for mutable operations.
**(C)** (suggested in https://github.com/ipfs/ipfs-companion/issues/285#issuecomment-333302914) Warn the user on startup that the gateway is not writable, so some applications may fail, with instructions on how to make it writable.

Any thoughts? 

cc @skorokithakis (ipfessay)

References:

- [What is a Writeable Gateway?](https://discuss.ipfs.io/t/writeable-http-gateways/210?u=lidel)
- [Is there any public writable gateway?](https://discuss.ipfs.io/t/is-there-any-public-writable-gateway/1140?u=lidel)

**Comment by skorokithakis** [comment]
Another alternative is to warn the user on startup that the gateway is not writable, so some applications may fail, with instructions on how to make it writable.

Also, if the publish button just does nothing, it's also a bug in IPFessay, as we aim to show a pop-up with instructions on getting to a writable gateway. Can you file a bug on IPFessay with steps to reproduce so we can fix it if you aren't getting the pop-up?

**Comment by lidel** [comment]
Thanks! Filled a bug at:  https://gitlab.com/stavros/IPFessay/issues/10 and added **(C)**.
However, I feel **(A)** may be better solution:  it delivers information at the right moment (just-in-time feedback), instead of pushing information to all users without any consideration if/when they really need it.

**Comment by lgierth** [comment]
The writable gateway hasn't gotten any love in over 2 years, but although it's not gonna get dropped, I'd rather have a UX scheme for using pinning services. Combined with adding to the embedded js-ipfs node (or an external ipfs node), this gets us closer to nice UX.

The more we can use embedded/external ipfs nodes instead the gateway, the better.

**Comment by lidel** [comment]
Indeed. I think the current approach for writable gateways is good enough. Let's close this.

FYSA if gateway is not writable, IPFessay displays:

> ![](https://gitlab.com/stavros/IPFessay/uploads/708290197ca498c3e4a947525d909392/2017-09-30-211306_471x175_scrot.png)
