### ISSUE TITLE
webui, url localhost:5001/webui wrong

### ISSUE THREAD

**Issue by flowpoint** [ipfs/ipfs-companion#291]
when accessing webui via, "localhost:5001/webui", i land at the url but with port 8080.
so: http://127.0.0.1:8080/ipfs/hash/#/
instead of http://127.0.0.1:5001/ipfs/hash/#/
using go-ipfs 0.4.11 as systemservice with the ipfs companion extension 2.0.12

**Comment by lidel** [comment]
What if we normalize `127.0.0.1` and always change it to `localhost` ?
It improves the Location Bar a bit, less scary for non-technical users.

**Comment by lidel** [comment]
@flowpoint No one picked this up, so I've fixed it in  [v2.1.1beta3](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/versions/beta), give it a try :)

**Comment by flowpoint** [comment]
works
