### ISSUE TITLE
Simplify UX Around The State Of Gateway Redirect

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-companion#325]
Based on anecdotal evidence  🙃  less savvy users are often confused about "gateway redirect".
It is mostly my fault. The term is used due to legacy reasons:  initial name of this add-on was "ipfs-gateway-redirect".

To make things worse, current GUI always displays  local gateway as "HTTP GATEWAY", no matter if it is actually used (enabled via redirect) or not:

> Enabled: ![2017-12-03-001242_1147x1421_scrot](https://user-images.githubusercontent.com/157609/33520618-dfcaf5f8-d7be-11e7-9f91-2119a4793c86.png)
> Disabled: ![2017-12-03-001230_1147x1421_scrot](https://user-images.githubusercontent.com/157609/33520619-e3352b0a-d7be-11e7-8e97-566d21437100.png)

## Here's an Idea

"HTTP Gateway" should reflect the URL of  currently _active_ gateway:

- If redirect is enabled, its value is URL of "Custom Gateway" (eg. `http://127.0.0.1:8080`)
- If redirect is disabled, its value is URL of "Public Gateway"  (eg. `https://ipfs.io`)

Additionally, we could rename toggle to make it self-explanatory and easier to understand:

- "Enable Gateway Redirect"  → "Switch to Custom Gateway"
- "Disable Gateway Redirect" → "Switch to Public Gateway"

If we make these two changes, then we can decrease cognitive load by removing "Redirect" status from UI.

**Comment by diasdavid** [comment]
@lidel I like this proposal 👍

**Comment by lidel** [comment]
Done! 

* This change is in [v2.1.1beta3](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/versions/beta) 🌵  
* We may be missing translations for two labels. If anyone wants to help with translation, check https://crowdin.com/project/ipfs-companion
* UX note: at some point in future, during general polish, we may consider cheating a bit, and displaying public gw immediately, instead of waiting for actual switch to propagate to the background page. 

![peek 2017-12-08 00-06](https://user-images.githubusercontent.com/157609/33743122-be37e78e-dbab-11e7-80ed-5e07a0b6adc2.gif)

**Comment by olizilla** [comment]
I'm all for this! #320 has got too big! I'd included a similar change there, but it's trapped in a larger changeset.

<img width="657" alt="screenshot 2017-12-11 09 47 19" src="https://user-images.githubusercontent.com/58871/33825155-9cc8131c-de58-11e7-9970-e2ca981c91b5.png">

I love how similar these changes have turned out. Feels like we're heading in the same direction!
