### ISSUE TITLE
can local node not participate in distribution of global data and only get locally requested data?

### ISSUE THREAD

**Issue by rezad1393** [ipfs/ipfs-companion#327]
I have metered internet(living in third world country :( ) .
so participating in the network on ipfs would not really be possible for me (the same reason for BitTorrent).
my question is can I use ipfs as an almost static repository that stores the data that I request when browsing but not upload them ?

**Comment by lidel** [comment]
Hi, try running `go-ipfs` daemon with `--routing=dhtclient` parameter.
This will prevent your daemon from participating in the DHT as a server (saves bandwidth and will actually make the network faster as we'll have fewer flaky DHT nodes). I use it on my laptop to save battery.

ps. I am closing/locking this issue, as it is not related to browser extension and we want to keep this repo on topic. If you need further support ask questions at https://discuss.ipfs.io more community members will see it there  :)
