### ISSUE TITLE
Husky is over excited.

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-companion#334]
Any objections to removing

```json
    "postcheckout": "npm update && run-s clean build:copy*",
    "postmerge": "run-s postcheckout",
```

from the the `package.json` ?

I've been running into issues where I can't run rebase as it triggers postcheckout and errors, which then stops the rebase halfway through...

```sh
❖ ~/Code/ipfs/ipfs-companion on feat/upload-dashboard 
$ git rebase master
First, rewinding head to replay your work on top of it...
husky > npm run -s postcheckout (node v8.9.3)

husky
uninstalling Git hooks
done

# Much module build noise trimmed...
 
3 warnings generated.
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/secp256k1.node
+ ipfs-api@17.1.3
added 3 packages, removed 1517 packages and updated 119 packages in 33.755s
sh: run-s: command not found

husky > post-checkout hook failed (add --no-verify to bypass)
could not detach HEAD
```

The trade off is we then have to remember to run `npm i` or `yarn` when we switch to a branch where the `package.json` or `yarn.lock` has changed. I'm ok with it if y'all are @lidel @alanshaw

**Comment by lidel** [comment]
Yeah it started slowing my work too now that we have multiple branches. 
Feel free to remove it 👍

**Comment by lidel** [comment]
@olizilla freel free to rebase on master – I just pushed commit that removes both hooks 🙂
