### ISSUE TITLE
Please add instructions on how to load the extension on Brave

### ISSUE THREAD

**Issue by diasdavid** [ipfs/ipfs-companion#340]
To the README https://github.com/ipfs/ipfs-companion#install

Bonus points for a gif!

Thank you ❤️

**Comment by olizilla** [comment]
![brave-ipfs-companion-4](https://user-images.githubusercontent.com/58871/34110877-e3080b0a-e3ff-11e7-8667-72fcef369386.gif)

**Comment by olizilla** [comment]
### Brave

`ipfs-companion` works in Brave. To try it out today you need to run brave from source, but we are working with Brave to get seamless IPFS support working out of the box. Track our progress [here](https://github.com/ipfs/ipfs-companion/issues/312)

- Configure your local ipfs gateway to run on port 9090 (_the default, port 8080, conflicts with the brave webpack dev server_)
- Clone and build `ipfs-companion` as above
- Clone [`brave/browser-laptop`](https://github.com/brave/browser-laptop)
- Symlink the `ipfs-companion/add-on` dir to `browser-laptop/app/extensions/ipfs`
- Add the following to `browser-laptop/app/extensions.js`
```js
  // Enable IPFS
  extensionInfo.setState('ipfs', extensionStates.REGISTERED)
  loadExtension('ipfs', getExtensionsPath('ipfs'), undefined, 'component')
```
https://github.com/ipfs-shipyard/browser-laptop/blob/66f38870fced0dbc55aae7fe1ed905bff602f88e/app/extensions.js#L500-L502
- In the `browser-laptop` project run `npm install` then in separate shells run `npm run watch` and `npm start`. If you have any trouble running Brave from source, check: https://github.com/brave/browser-laptop#installation

Brave will start up and you should see a badge with your number of connected ipfs peers next to the brave button, top right. (_the ipfs-companion badge [currently doesn't appear]()_). Click on the badge and update your gateway settings to use port `9090`, then go share something with your peers...

![brave ipfs](https://user-images.githubusercontent.com/58871/34110877-e3080b0a-e3ff-11e7-8667-72fcef369386.gif)
