### ISSUE TITLE
Handle "/ipfs/" in browser search bar

### ISSUE THREAD

**Issue by hazae41** [ipfs/ipfs-companion#417]
It currently handles "ipfs://" "ipns://" "dweb:" but not "/ipfs/"

**Comment by lidel** [comment]
While  there is no API to do it in a humane way, we could re-use hack from https://github.com/ipfs-shipyard/ipfs-companion/issues/164#issuecomment-328374052 

The question is: should we? 

Pros: Improved UX for NURIs on Firefox and Chrome (eg. quick copy&paste)
Cons: Won't work not on Android

**Comment by Hazae41** [comment]
It does not matter to Android, he will follow his big brothers (or big browsers (; )
