### ISSUE TITLE
Add Namecoin support

### ISSUE THREAD

**Issue by hazae41** [ipfs/ipfs-companion#577]
It would be cool if DNSLink could resolve TXT records of Namecoin's .bit domains

**Comment by lidel** [comment]
cc https://github.com/ipfs/notes/issues/41

**Comment by Hazae41** [comment]
So what's the status of this feature?
Is it in development?
How can we help?

**Comment by lidel** [comment]
I am not aware of any active development, but PRs are welcome.

Support for namecoin lookups needs to be added to [`ipfs.dns` API](https://github.com/ipfs/interface-ipfs-core/blob/f3081ab12a28d84869740bb38a20bd294e05aa40/SPEC/MISCELLANEOUS.md#dns) provided by go-ipfs and  js-ipfs.
When that lands, then browser extension will be able to support it as well.
