### ISSUE TITLE
Fallback to Embedded when External is not available

### ISSUE THREAD

**Issue by hazae41** [ipfs/ipfs-companion#661]
Hello, it would be useful if IPFS Companion were to automatically run the Embedded node when the External node is not available, then kill the Embedded when the External becomes available. 

Thanks 👍

**Comment by lidel** [comment]
When js-ipfs 0.34 is released, we  will be able to use Web UI with it (https://github.com/ipfs-shipyard/ipfs-companion/pull/656), so it will be safe to do suggested fallback, however we need to update onboarding screen to account for it.

Right now, when a new user installs this extension, they are greeted with welcome page informing them they don't have daemon running: 

![welcome screen when HTTP API is down](https://user-images.githubusercontent.com/33324750/45353988-749d3280-b5b4-11e8-8773-cd222ac137a1.png)

When daemon is started, then the screen changes to:

![welcome screen when API is online](https://user-images.githubusercontent.com/33324750/45353977-6ea75180-b5b4-11e8-9252-53731b311c01.png)


If we automatically fallback to js-ipfs, user will immediately see the success one, and won't learn about existence of option to use standalone daemon (in the future we will replace shell commands  with information about [ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop)).

@olizilla @fsdiogo @alanshaw  would appreciate some feedback on how to handle this change. 

My initial idea, is that fallback to js-ipfs should be an opt-in setting on Preferences screen (below "Automatic Mode"). 

There should also be a button on the welcome screen to do the opt-in (forgive quick&ugly mockup):

<img width="1359" alt="45353988-749d3280-b5b4-11e8-8773-cd222ac137a1" src="https://user-images.githubusercontent.com/157609/51287345-54183580-19f7-11e9-8558-53e25e555916.png">

When user clicks "start js-ipfs" button, they get the ["success screen"](https://user-images.githubusercontent.com/33324750/45353977-6ea75180-b5b4-11e8-9252-53731b311c01.png) and can start using IPFS.

Is there a better way to handle or communicate this?
