### ISSUE TITLE
Prevent mixed content warnings for TLS sites embedding ipfs URIs

### ISSUE THREAD

**Issue by the8472** [ipfs/ipfs-companion#75]
Adding `nsiProtocolHandler.URI_SAFE_TO_LOAD_IN_SECURE_CONTEXT` to the handlers should allow the URI schemes to be used to load subresources into secure contexts.

Public gateways use TLS anyway and thus can already be embedded as 3rd party content. Private gateways hopefully are under control of the user / in a trusted network.

**Comment by lidel** [comment]
I am okay with adding the flag: content-addressing provides better protection against MITM than TLS  anyway (as long as user controls the gateway).
  
We probably need to add a new section to [SECURITY.md](https://github.com/lidel/ipfs-firefox-addon/blob/master/SECURITY.md) and  explicitly advise people against use of custom gateways outside of their control.

**Comment by Kubuxu** [comment]
It would be great to have this, currently for example https://ipfs.pics doesn't work on the redirect, one has to use http version which is much much worst.

Also FF people are considering making all localhost as trusted content, only opposition are those who want to block browser off localhost completely. https://bugzilla.mozilla.org/show_bug.cgi?id=903966

**Comment by lidel** [comment]
@Kubuxu 
> https://ipfs.pics doesn't work on the redirect

I tried to replicate, but https://ipfs.pics/QmR48aP79GaXfs5rh469kAJw9wDLA5yYrcgsL5gyuQjmBe loads http://127.0.0.1:8080/ipfs/QmR48aP79GaXfs5rh469kAJw9wDLA5yYrcgsL5gyuQjmBe just fine, the only drawback is mixed-content warning: 

> ![2016-06-20-204825_328x35_scrot](https://cloud.githubusercontent.com/assets/157609/16206356/57d3c27a-3728-11e6-9928-15597c75dc04.png)

Am I missing something?

**Comment by Kubuxu** [comment]
Hmm, I thought it was blocking the mixed content completely but it looks like it works now.

Sorry for that.

**Comment by lidel** [comment]
Update via https://bugzilla.mozilla.org/show_bug.cgi?id=903966#c14:
> According to the spec, content from loopback addresses should no longer
be treated as mixed content even in secure origins. See:
> - https://github.com/w3c/webappsec-mixed-content/commit/349501cdaa4b4dc1e2a8aacb216ced58fd316165
> - https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy

> Note that we only whitelist '127.0.0.1' and '::1' to match Chrome 53 and
later. See:
> - https://chromium.googlesource.com/chromium/src.git/+/130ee686fa00b617bfc001ceb3bb49782da2cb4e

**Comment by lidel** [comment]
I just confirmed that there is no "mixed content" warning under Firefox 55 and Chrome 53 when using local (`127.0.0.1`) gateway.

**Comment by ivan386** [comment]
I install stunnel on [8443 port](https://github.com/ivan386/stunnel-settings-for-ipfs/blob/master/stunnel.conf) and [make certificate](https://github.com/ivan386/stunnel-settings-for-ipfs/blob/master/makecert.cmd) for 127.0.0.1 and other domains. Root certificate (rootcert.pem or rootcert.crt) need to be added to trusted certificate repository. Then site can [detect by JavaScript that local gateway available](https://github.com/ivan386/IPFS-local-gateway-detect/blob/master/redirect_to_ipfs_gateway.js) on 8443 port and switch to it.
