### ISSUE TITLE
Utility IPFS Service crashes immediately in Brave

### ISSUE THREAD

**Issue by morbility** [ipfs/ipfs-companion#978]
**Describe the bug**
Utility IPFS Service crashes immediately in Brave, this in turn causes the mouse pointer to constantly flash busy.

**Expected behavior**
Utility IPFS Service to stay running and not cause pointer to flash.

**Desktop (please complete the following information):**
 - OS: Windows 10 (19042.746)
 - Browser: Brave
 - Version V1.19.88

IPFS: 2.17.2
![Screenshot 2021-01-30 023700](https://user-images.githubusercontent.com/13098396/106354108-39465000-62a4-11eb-9501-704a104da72b.jpg)

![Screenshot 2021-01-30 023428](https://user-images.githubusercontent.com/13098396/106354104-33506f00-62a4-11eb-8b1a-33043d905498.jpg)

**Comment by jessicaschilling** [comment]
This isn't an error seen before. Please start by uninstalling and reinstalling Companion.

**Comment by lidel** [comment]
@morbility Did you enable IPFS support in  Brave (either via dropbar or settings)?
