### ISSUE TITLE
Allowing requests to http (no SSL) gateways

### ISSUE THREAD

**Issue by ThomasFreedman** [ipfs/ipfs-companion#987]
**Is your feature request related to a problem? Please describe.**
I am working on a project to build portable IPFS nodes on Raspberry Pi computers. They are not intended to be on a domain so LetsEncrypt + proxy such as Nginx is not a viable solution. A use case would be a family or small group of room mates want to use one of these as their local gateway and connect to it from their own laptop using IPFS Companion. However IPFS companion does not recognize the exposed 0.0.0.0:8080 gateway.

**Describe the solution you'd like**
A checkbox or other means to allow IPFS Companion to recognize and use non-ssl secured http gateways.

**Describe alternatives you've considered**
Using self-signed certificates with nginx proxy but IPFS Companion treats those (rightly) the same as http.

**Additional context**

**Comment by lidel** [comment]
`0.0.0.0:8080` is not a valid IP, browser will normalize it to localhost of the machine with Companion, instead of a LAN IP of Raspberry Pi.

What you should enter in Companion is the LAN IP of Raspberry machine like `http://192.168.0.42:8080` or similar.
A warning about mixed content will be displayed, but if you are ok with related limitations (details below), things will work.

----- 

There is a limitation of the web platform that requires a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) for some features to work.
This is a limitation introduced by your web browser, not Companion extension. We are unable to work around this.
Running in LAN without TLS means your gateway is still marked as insecure context. 

This means you either need to have TLS set up, or run on localhost (or tunnel gateway port from rpi to localhost, so it _looks_ like localhost).

**Comment by ThomasFreedman** [comment]
Unfortunately using "http://192.168.0.42:8080 or similar" isn't universal as 0.0.0.0 is. 0.0.0.0 is generally recognized (i.e. docker) as a wildcard IP address. The solution you suggest also only works for all systems with static IP addresses, which my project  is not focused on.

I can appreciate a secure context is required "for some features" to work, but does IPFS Companion need to be one of them? I don't believe so.

You're saying it's the browser that maps a 0.0.0.0 address to localhost. Ok, I have no reason to doubt you on that. However, as IPFS Companion has the ability to determine the current LAN IP address it could do the mapping from 0.0.0.0 to what it determines is the LAN IP address _when the request is made_, and pass that to the browser instead, if the IPFS Companion configuration specifies an http://0.0.0.0:<port>/ gateway.

IPFS Companion could manage detecting a dynamic IP of the host it is running on to provide a gateway for the LAN it operates on. 

Please consider re-opening this issue to address this need.

**Comment by lidel** [comment]
> I can appreciate a secure context is required "for some features" to work, but does IPFS Companion need to be one of them? I don't believe so.

We are not blocking anything in Companion. You can use insecure URLs if you want.
Companion only displays a warning on _Preferences_ screen informing about mixed-content issues, that is all.

> IPFS Companion could manage detecting a dynamic IP of the host it is running on to provide a gateway for the LAN it operates on.
> Please consider re-opening this issue to address this need.

I feel I am missing all the context, please let me know if I got your feature request right.
My understanding is:
- You have Companion and go-ipfs running on the same machine
- Companion is connected to go-ipfs over `https://127.0.0.1:5001`
- go-ipfs Gateway is listening on  all interfaces (`http://0.0.0.0:8080`)
- You want Companion to automatically detect LAN IP by reading  IP from  `Addresses` via `ipfs id` and reading port via `ipfs config` and  use it for Gateway in Companion, so you can see it in the status in the browser action menu, and can share that address with other people in your LAN. 

Is this correct?

The problem I see with this  is that depending on your ISP, you can be behind more than one NAT, and/or have multiple IPs from different [private networks](https://en.wikipedia.org/wiki/Private_network) and there is no way to tell which one is the LAN you care about.

**Comment by ThomasFreedman** [comment]
You understood my request perfectly. Regarding the multiple NAT concern, only the inner most network IP address is necessary, that is what I refer to as the local LAN.
Basically when the 0.0.0.0 address is configured as the gateway, it should trigger companion to replace it when a request is made (as DHCP addresses change from tie to time) with the IP value of the local host, for example the same IP address reported by ifconfig in Linux or ipconfig on Windows.
Whether IPFS Companion has a role in that or it is a matter of the gateway code of the IPFS daemon I can't be certain. It's a matter of configuring the gateway listener address to be dynamic rather than hard coded to a specific IP address. 
When you see a 0.0.0.0 for a listener in the netstat program it corresponds to "this host's current IP address".
-------------------------------------------------------------------------
1) This private E-mail including but not limited to any / all attachment(s), are lawfully protected in any public jurisdiction subject to 1a.
2) Nunc pro tunc "Now for Then" (retroactive):  All Rights Reserved (Without Prejudice(2a)), Non Assumpsit(2b), and Without the United States(2c)1a) Electronic Communications Privacy Act, 18 U.S.C. § 2510-2521
2a) Without Prejudice UCC 1-308, UCC 1-306.6, in other words: All Rights Reserved
2b) Non Assumpsit "Did not undertake" (compulsory contracts)
2c) United States as defined by 26 USC § 77012c § 7701.9) Legalese: “The United States government is a foreign corporation with respect to a state" (20 C.J.S. Corporations §1785)
2c § 7701.10) Legalese: "include" in Latin: "expressio unius est exclusio alterius" or "to express or include one thing implies the exclusion of the other." Black's Law Dictionary (8th, 9th ed. 2009)

3) The color of the text above designates political jurisdiction: red-private non-statutory, flesh and blood, man / woman, blue-administrative, admiralty law, corporate jurisdiction. These are also pen ink colors and are significant on legal documents. Underlined text are links to further information.

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lidel** [comment]
>  only the inner most network IP address is necessary, that is what I refer to as the local LAN

AFAIK browser extension is unable to tell which is inner, and which is outer, 
nor  go-ipfs expose any API that we could use for determining this. 

In the past we could use webrtc for learning about local IP, but many vendors identify this as a security risk  and obfuscate it, making it unfeasible:

- https://groups.google.com/g/discuss-webrtc/c/4Yggl6ZzqZk/m/nV24XkXXAQAJ
- https://stackoverflow.com/questions/56755747/rtcicecandidate-no-longer-returning-ip

Unless you see a way around this, I don't think we can solve this  without introducing changes to go-ipfs.

----

I am still confused about network topology you are solving for. Perhaps there is an easier way to deliver what you need. If you are building portable IPFS nodes on Raspberry Pi computers, then are you running Companion on them as well?

**Comment by ThomasFreedman** [comment]
Ok, thx for the update. I'll look into this when I return and see if there is any way to determine the machine's IP address from go or browser context.
Seems a bit odd such a thing wouldn't be discoverable.

-------------------------------------------------------------------------
1) This private E-mail including but not limited to any / all attachment(s), are lawfully protected in any public jurisdiction subject to 1a.
2) Nunc pro tunc "Now for Then" (retroactive):  All Rights Reserved (Without Prejudice(2a)), Non Assumpsit(2b), and Without the United States(2c)1a) Electronic Communications Privacy Act, 18 U.S.C. § 2510-2521
2a) Without Prejudice UCC 1-308, UCC 1-306.6, in other words: All Rights Reserved
2b) Non Assumpsit "Did not undertake" (compulsory contracts)
2c) United States as defined by 26 USC § 77012c § 7701.9) Legalese: “The United States government is a foreign corporation with respect to a state" (20 C.J.S. Corporations §1785)
2c § 7701.10) Legalese: "include" in Latin: "expressio unius est exclusio alterius" or "to express or include one thing implies the exclusion of the other." Black's Law Dictionary (8th, 9th ed. 2009)

3) The color of the text above designates political jurisdiction: red-private non-statutory, flesh and blood, man / woman, blue-administrative, admiralty law, corporate jurisdiction. These are also pen ink colors and are significant on legal documents. Underlined text are links to further information.

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
