### ISSUE TITLE
Sharp (#) in url is not handled elegantly

### ISSUE THREAD

**Issue by proletarius101** [ipfs/ipfs-companion#989]
**Describe the bug**
If there's a # in the url (e.g. http://element-web.0x1a8510f2.space.ipns.localhost:8081/#/welcome), it can't be pinned with ipfs companion.

**To Reproduce**
1. Go to `http://element-web.0x1a8510f2.space.ipns.localhost:8081/#/welcome`
2. Click on 'Pin IPFS Recource'
3. Open ipfs-companion panal again
4. It shows it's not pinned

**Expected behavior**
http://element-web.0x1a8510f2.space.ipns.localhost:8081/#/welcome should be pinned as `/ipns/element-web.0x1a8510f2.space`. That is, it should strip the # suffix, because they are not part of the path in the resource

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Of course, 
````
ipfs pin add /ipns/element-web.0x1a8510f2.space/#/welcome
Error: no link named "#" under QmSmQSREw7PtCNLDC4LxAoi8eWwj3tSCtJGaqXJFjKwA5S
````
But many sites redirects to a # url automatically. And the ipfs companion's pinning workflow doesn't allow editing.

**Comment by lidel** [comment]
I believe this is no longer an issue since #810 replaced pinning with import to IPFS.
