### ISSUE TITLE
Notifications on Linux

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [ipfs/ipfs-companion#995]
Os: Arch Linux
Wm: AwesomeWM
Browser: Firefox 88
IPFS-Companion: 2.18.0

IPFS-Companion should use native OS notification system (notify-send) instead of stubbornly using its own on Linux, like everything else on my system does. Also, as I'm using a dual-head system, for some weird reason IPFS-Companion notifications are always shown on the secondary screen, although Firefox is open (and focused) on the primary screen.

**Comment by lidel** [comment]
Sadly this is not something we can fix in IPFS Companion.
Ut uses API provided by the browser, in your case Firefox.

If you want this fixed, please describe  your dual-monitor bug in Firefox bugtracker:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1383964
