### ISSUE TITLE
Extensions causing ERR_BLOCKED_BY_CLIENT (I guess) and huge page load times 

### ISSUE THREAD

**Issue by ruifortes** [ipfs/ipfs-companion#998]
The extensions is always running in my browser (Brave) but just now it started doing this and.... "really just now" it stopped?!?!

I don't get why the intermitence of this fenomenon but just minutes ago I was switching the extension on and off and the problem would stop and come back accordingly

I've have these intermitent slowdowns for a while but was attributting it to some throtling by the ISP.

Anyone experienced this?

PS: This and the [CPU spikes](https://github.com/ipfs/go-ipfs/issues/7854) makes me wonder.... about CIA moles :-P
   ....also ERR_BLOCKED_BY_CLIENT might be a little "clickbaity" cause I don't really know what's causing it

**Comment by lidel** [comment]
@ruifortes  thank you for filling this. ERR_BLOCKED_BY_CLIENT is Chromium error  – usually means that one of browser extensions you have is blocking something. It could be uBlock, PrivacyBadger, or in Brave,the built-in adblocker (Shields?) . Brave has similar bug before (https://github.com/brave/brave-browser/issues/13641), so if you are able to reproduce the problem reliably without any other extensions, please fill a bug in  https://github.com/brave/brave-browser/issues/ 

I'm closing issue here: 
- Companion can't do anything about rules set in Brave
- Slowdowns are not related to Companion, but interaction between go-ipfs and your ISP
